import type { DesktopSnapshot } from "../../types";

export const demoSnapshot: DesktopSnapshot = {
  activeProfileId: "wx-retail",
  proxyStatus: "stopped",
  certificate: {
    generated: false,
    trusted: false,
    fingerprint: "Not generated",
  },
  profiles: [
    {
      id: "wx-retail",
      name: "零售小程序",
      domain: "api.dev.acme.test",
      port: 8899,
      apifox: {
        mode: "online",
        source: "Project #981245",
        mockPrefix: "https://m1.apifoxmock.com/m1/981245-0-default",
        selectedTags: ["商品", "订单"],
      },
      rules: [
        {
          id: "product-list",
          name: "商品列表",
          method: "GET",
          path: "/v1/products",
          matchMode: "exact",
          target: "https://m1.apifoxmock.com/m1/981245-0-default/v1/products",
          enabled: true,
          tag: "商品",
        },
        {
          id: "order-create",
          name: "创建订单",
          method: "POST",
          path: "/v1/orders",
          matchMode: "exact",
          target: "https://m1.apifoxmock.com/m1/981245-0-default/v1/orders",
          enabled: true,
          tag: "订单",
        },
        {
          id: "coupon-query",
          name: "优惠券查询",
          method: "GET",
          path: "/v1/coupons",
          matchMode: "contains",
          target: "https://m1.apifoxmock.com/m1/981245-0-default/v1/coupons",
          enabled: false,
          tag: "营销",
        },
      ],
    },
    {
      id: "wx-member",
      name: "会员中心",
      domain: "member.dev.acme.test",
      port: 8899,
      apifox: {
        mode: "local",
        source: "http://127.0.0.1:4523/export/openapi.json",
        mockPrefix: "http://127.0.0.1:4523/m1/77215-0-default",
        selectedTags: ["会员"],
      },
      rules: [],
    },
  ],
  logs: [
    {
      id: "log-1",
      createdAt: "10:42:16.310",
      method: "GET",
      source: "api.dev.acme.test/v1/products?page=1",
      destination: "m1.apifoxmock.com/m1/981245-0-default/v1/products?page=1",
      ruleName: "商品列表",
      status: "matched",
      responseCode: 200,
      duration: 184,
    },
    {
      id: "log-2",
      createdAt: "10:41:58.905",
      method: "POST",
      source: "api.dev.acme.test/v1/orders",
      destination: "m1.apifoxmock.com/m1/981245-0-default/v1/orders",
      ruleName: "创建订单",
      status: "matched",
      responseCode: 201,
      duration: 267,
    },
    {
      id: "log-3",
      createdAt: "10:40:11.440",
      method: "GET",
      source: "api.dev.acme.test/v1/notice",
      destination: "api.dev.acme.test/v1/notice",
      ruleName: "未命中",
      status: "passed",
      responseCode: 200,
      duration: 96,
    },
  ],
};
